name: my_llm_app
description: A new Flutter project

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.18.0

flutter:
  uses-material-design: true
